const readonly = 'readonly';
export default [
  { ignores: ['node_modules/**', 'dist/**', 'drizzle/**', '.cache/**', '.local/**'] },
  {
    files: ['**/*.js', '**/*.mjs'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        console: readonly,
        process: readonly,
        Buffer: readonly,
        URL: readonly,
        Request: readonly,
        Response: readonly,
        Headers: readonly,
        TextDecoder: readonly,
        AbortController: readonly,
        fetch: readonly,
        structuredClone: readonly,
        crypto: readonly,
        setTimeout: readonly,
        clearTimeout: readonly,
        document: readonly,
        window: readonly,
        localStorage: readonly,
        location: readonly,
        confirm: readonly,
      },
    },
    rules: {
      'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      'no-undef': 'error',
      'no-var': 'error',
      'prefer-const': 'error',
      eqeqeq: 'error',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-empty': 'error',
      'no-unreachable': 'error',
      'no-constant-condition': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-imports': 'error',
    },
  },
];
