export const defaults = {
  production: {
    company: 'Globalporc SL',
    year: 2025,
    crop: 'Ametlla',
    area: 32,
    income: [
      { name: 'VAIRO', quantity: 30441, price: 5.3, amount: 161446, mode: 'manual' },
      { name: 'LAUREANNE', quantity: 14601, price: 5.2, amount: 75926, mode: 'manual' },
      { name: 'GUARA', quantity: 24978, price: 5.2, amount: 129885.6, mode: 'calculated' },
      { name: 'AGROSEGURO', quantity: 0, price: 0, amount: 0, mode: 'manual' },
      { name: 'SUBVENCIONS', quantity: 0, price: 0, amount: 0, mode: 'manual' },
      { name: 'FINANCERS', quantity: 0, price: 0, amount: 20438.49, mode: 'manual' },
    ],
    expenses: [
      ['Fungicides', 9612],
      ['Insecticides', 1391],
      ['Adobs', 24964],
      ['Quelats', 1547],
      ['Herbicides', 2368],
      ['Reguladors', 258],
      ['Adobs foliars', 1928],
      ['Poda', 0],
      ['Poda mecanica', 0],
      ["Recol·lecció. Ma d'obra.", 0],
      ['Recol·lecció x 3rs', 0],
      ['Esclarir', 0],
      ['Lligar', 0],
      ['Pol·linització', 2000],
      ['Replantar. Arbres.', 0],
      ["Replantar. Ma d'obra.", 0],
      ['Despeses de pelar.', 3998],
      ["Despeses d'assecatge.", 2004],
      ['Despeses molturació', 0],
      ['Transport x 3rs.', 0],
      ['Manteniment.', 0],
      ["C Regants d'Alcarras", 0],
      ['Altres despeses.', 0],
    ]
      .map(([name, amount]) => ({ name, amount, group: 'production' }))
      .concat(
        [
          ['IBI RUSTICA', 0],
          ['C. REGANTS MONTAGUT', 0],
          ['C. REGANTS PINYANA', 0],
          ['C. REGANTS VALLMANYA', 0],
          ['REPARACIONS', 0],
          ['AGROSEGURO', 3400],
          ['GAS-OIL', 0],
        ].map(([name, amount]) => ({ name, amount, group: 'general' })),
      ),
  },
  npk: {
    company: 'GLOBAL',
    farm: 'PARCELA',
    sector: '9',
    variety: 'HONEY GLO',
    area: 1.4,
    n: 120,
    p: 40,
    k: 240,
    days: 105,
    flow: 2,
    fertilizers: [
      { name: 'Adob complex', basis: 'k', n: 2, p: 2, k: 9, price: 0, density: 1.2, kgHa: 0 },
      { name: 'N-20', basis: 'n', n: 20, p: 0, k: 0, price: 0, density: 1.2, kgHa: 0 },
    ],
  },
};
